// Code generated by command: go run transform_amd64_asm.go -out ../transform_amd64.s -stubs ../transform_amd64.go -pkg curl. DO NOT EDIT.

//go:build amd64 && gc && !purego

package curl

// transform transforms the sponge state. It works like transformGeneric.
//go:noescape
func transform(lto *[729]uint, hto *[729]uint, lfrom *[729]uint, hfrom *[729]uint)
