name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-go@v1
      with:
        go-version: 1.21

    - name: Run Tests
      run: |
        go test ./...
        go vet ./...
